language: rust
cache: cargo

matrix:
  include:

    - rust: stable
      script:
        - cargo test
        - rustup component add rustfmt-preview
        - cargo fmt --all -- --check
    - rust: beta
      script:
        - cargo test
    - rust: nightly
      script:
        - cargo test

allow_failures:
  - rust: nightly