[package]
name = "bench"
version = "0.1.0"
authors = ["gngeorgiev <gngeorgiev.it@gmail.com>"]
edition = "2018"

[dependencies]
semver = "1.0.4"
semver_rs = { path = "../" }
easybench = "1.1.0"
alloc_counter = "0.0.4"
regex = "1.5.4"
clap = "2.33.3"
